import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  slide: {
    flex: 1,
    paddingHorizontal: 28,
    paddingVertical: 40,
  },
  logoSlide: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 80,
  },
  brandLetter: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 58,
    color: '#F6EBC6',
    letterSpacing: 8,
    textTransform: 'lowercase',
  },
  brandRest: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 58,
    color: '#F6EBC6',
    letterSpacing: 8,
    textTransform: 'lowercase',
    marginLeft: 8,
  },
  brandDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: '#F6EBC6',
    marginHorizontal: 10,
  },
  logoFooter: {
    alignItems: 'center',
    marginBottom: 24,
  },
  footerLine: {
    width: 76,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 18,
  },
  tagline: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 16,
    color: '#EDE6FF',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  paginationDot: {
    width: 26,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#FFFFFF',
  },
  messageSlide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge: {
    width: 260,
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 56,
  },
  badgeRing: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  badgeInner: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'rgba(9, 7, 19, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeOrb: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(133, 133, 168, 0.65)',
    left: 55,
    top: 120,
  },
  badgeTag: {
    position: 'absolute',
    top: 50,
    right: 75,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  badgeTagLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#FFFFFF',
  },
  headline: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 28,
    lineHeight: 38,
    color: '#F5F1FF',
    textAlign: 'center',
  },
  highlight: {
    color: '#F6EBC6',
  },
  subline: {
    marginTop: 18,
    fontFamily: 'Poppins_500Medium',
    fontSize: 18,
    color: '#F5B7D1',
  },
  ctaWrapper: {
    width: '100%',
    marginTop: 36,
    paddingHorizontal: 28,
  },
  ctaButton: {
    width: '100%',
    borderRadius: 40,
    paddingVertical: 18,
    paddingHorizontal: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ctaLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 18,
    color: '#FFFFFF',
  },
  ctaArrows: {
    flexDirection: 'row',
    gap: 6,
  },
  authContainer: {
    flex: 1,
    paddingHorizontal: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authHeadline: {
    marginTop: 40,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 26,
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 36,
  },
  authButtons: {
    width: '100%',
    marginTop: 36,
    gap: 16,
  },
  authButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 32,
    borderWidth: 1,
    justifyContent: 'center',
  },
  authButtonIcon: {
    marginRight: 10,
  },
  authButtonLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 16,
  },
  authNote: {
    marginTop: 18,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#C4C0DD',
    textAlign: 'center',
  },
  authTerms: {
    marginTop: 52,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#C4C0DD',
    textAlign: 'center',
    lineHeight: 20,
  },
  link: {
    color: '#F5B7D1',
  },
  btContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 24,
  },
  btContent: {
    paddingBottom: 56,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  btWelcome: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 28,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  btSubHeading: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 16,
    color: '#B4AED0',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 10,
  },
  btIntroCard: {
    marginTop: 20,
    padding: 24,
    borderRadius: 24,
    backgroundColor: 'rgba(20, 16, 32, 0.85)',
  },
  btIntroTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 18,
    color: '#F5B7D1',
    marginBottom: 16,
  },
  btBulletList: {
    gap: 8,
  },
  btBullet: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    color: '#E5E2F6',
  },
  btPrimaryButton: {
    marginTop: 24,
    backgroundColor: '#F6EBC6',
    paddingVertical: 16,
    borderRadius: 32,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  btPrimaryLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#1C142F',
  },
  btSearchWrapper: {
    marginTop: 18,
  },
  btNote: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#D4CFE8',
    textAlign: 'center',
  },
  btScanning: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#8E8BB2',
    textAlign: 'center',
    marginTop: 8,
  },
  devicesCard: {
    marginTop: 28,
    borderRadius: 28,
    backgroundColor: 'rgba(20, 16, 32, 0.85)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 8,
  },
  devicesHeader: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#E9E5FF',
    marginBottom: 6,
  },
  deviceRow: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deviceName: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#F2EEFF',
  },
  deviceStatus: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    marginTop: 4,
  },
  deviceActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btFooterText: {
    marginTop: 18,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#BEB9D4',
    textAlign: 'center',
    lineHeight: 22,
  },
  btSuccessWrapper: {
    marginTop: 25,
  },
  btSuccessCopy: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    color: '#C8C5DB',
    textAlign: 'center',
  },
  successCard: {
    marginTop: 24,
    borderRadius: 26,
    backgroundColor: 'rgba(20, 16, 32, 0.85)',
    padding: 20,
  },
  successCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  deviceStatusSuccess: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#58E0A8',
  },
  successButton: {
    marginTop: 28,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    alignItems: 'center',
  },
  successButtonLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#1C142F',
  },
  connectionCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    padding: 18,
  },
  connectionLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  connectionRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  connectionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 10,
  },
  stepDot: {
    width: 20,
    height: 4,
    borderRadius: 2,
    marginHorizontal: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  stepDotActive: {
    backgroundColor: '#FFFFFF',
  },
  profileContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 24,
  },
  profileScroll: {
    flex: 1,
  },
  profileBadge: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(123, 180, 255, 0.2)',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  profileSection: {
    gap: 16,
    marginBottom: 32,
  },
  profileTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 26,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  profileSubtitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    color: '#CFCBE3',
    textAlign: 'center',
  },
  formCard: {
    borderRadius: 28,
    backgroundColor: 'rgba(18, 14, 30, 0.9)',
    padding: 20,
    gap: 14,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
  },
  input: {
    flex: 1,
    color: '#FFFFFF',
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  inputHalf: {
    flex: 1,
  },
  genderPicker: {
    justifyContent: 'space-between',
  },
  genderText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#FFFFFF',
  },
  thresholdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  thresholdPlaceholder: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#B6AECF',
  },
  saveProfileButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    paddingVertical: 14,
    alignItems: 'center',
  },
  saveProfileLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#1C142F',
  },
  cancelProfileButton: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  cancelProfileLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#FFFFFF',
  },
  addProfileButton: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    paddingVertical: 14,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  addProfileText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#FFFFFF',
  },
  tipText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#C6C2DA',
    textAlign: 'center',
    lineHeight: 20,
  },
  profileHint: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 15,
    color: '#CFCBE3',
    textAlign: 'center',
  },
  profileListCard: {
    borderRadius: 26,
    backgroundColor: 'rgba(18, 14, 30, 0.9)',
    padding: 18,
    gap: 12,
  },
  addAnotherButton: {
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  profileCardItem: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    gap: 8,
  },
  profileCardActive: {
    borderColor: '#7DB4FF',
    backgroundColor: 'rgba(125, 180, 255, 0.08)',
  },
  profileCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  profileName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  profileMeta: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#C6C2DA',
  },
  profileThresholdRow: {
    flexDirection: 'row',
    gap: 6,
  },
  thresholdLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#B7B2CB',
  },
  thresholdValue: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#F5B7D1',
  },
  profileTempRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tempValue: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#E9E5FF',
  },
  selectBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectBadgeActive: {
    backgroundColor: '#7DB4FF',
    borderColor: '#7DB4FF',
  },
  summaryBadge: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#CCF5E9',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    padding: 18,
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  summaryTile: {
    borderRadius: 18,
    backgroundColor: 'rgba(64, 56, 80, 0.8)',
    padding: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  summaryTileHighlight: {
    borderWidth: 1,
    borderColor: '#7DB4FF',
  },
  summaryTileIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryTileTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  summaryTileSubtitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#BCB8CF',
    marginTop: 4,
  },
  summaryChecklist: {
    marginTop: 16,
    gap: 6,
  },
  checkItem: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#CBF0DA',
  },
  summaryHeadline: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 26,
    color: '#FFFFFF',
    marginTop: 8,
    textAlign: 'center',
  },
  summarySubhead: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#35D39C',
    marginTop: 4,
    textAlign: 'center',
  },
  dashboardButton: {
    marginTop: 24,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  dashboardButtonLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#1C142F',
  },
  dashboardContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  dashboardScroll: {
    flex: 1,
  },
  dashboardContent: {
    paddingBottom: 140,
    gap: 20,
  },
  dashboardContentAlt: {
    paddingTop: 16,
  },
  dashboardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  profileSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    minHeight: 48,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
  },
  profileSelectorLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#FFFFFF',
    maxWidth: 160,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  headerBattery: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F04E5A',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
  },
  headerBatteryText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
  },
  headerBluetooth: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(127, 219, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  tempCard: {
    borderRadius: 26,
    padding: 20,
    gap: 14,
  },
  tempCardBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tempCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tempValue: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 44,
    color: '#FFFFFF',
  },
  tempStateTag: {
    marginTop: 4,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#1F1F1F',
  },
  tempLiveContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tempLiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF5959',
  },
  tempLiveLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#FFFFFF',
  },
  tempSync: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: 'rgba(0,0,0,0.6)',
  },
  trendCard: {
    borderRadius: 28,
    backgroundColor: 'rgba(18, 14, 30, 0.9)',
    padding: 20,
  },
  trendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trendTabs: {
    flexDirection: 'row',
    gap: 8,
  },
  trendTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  trendTabActive: {
    backgroundColor: '#352949',
  },
  trendTabLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#B8B2CC',
  },
  trendTabLabelActive: {
    color: '#FFFFFF',
  },
  adjustLink: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#7EE1FF',
  },
  trendMode: {
    marginTop: 10,
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#9CE3B7',
  },
  trendDays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  trendDayLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#A7A3BE',
  },
  trendDayActive: {
    color: '#FFFFFF',
  },
  deviceHealthCard: {
    borderRadius: 28,
    backgroundColor: 'rgba(18, 14, 30, 0.9)',
    padding: 20,
    gap: 16,
  },
  sectionTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  deviceBattery: {
    borderRadius: 22,
    backgroundColor: 'rgba(122, 187, 255, 0.18)',
    padding: 16,
    gap: 6,
  },
  deviceBatteryTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#1C2D45',
  },
  deviceName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#1C2D45',
  },
  deviceBatteryValue: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 28,
    color: '#1C2D45',
  },
  batteryBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  batteryBarFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: '#1C2D45',
  },
  deviceActionsButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  deviceAction: {
    flex: 1,
    backgroundColor: '#F6EBC6',
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flexDirection: 'row',
  },
  deviceActionSecondary: {
    backgroundColor: '#FFE18A',
  },
  deviceActionLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#1C142F',
  },
  manageAccessCard: {
    borderRadius: 28,
    backgroundColor: 'rgba(18, 14, 30, 0.9)',
    padding: 20,
    gap: 16,
  },
  accessList: {
    gap: 14,
  },
  accessRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  accessInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  accessAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessAvatarText: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  accessName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  accessRole: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#B4B0C9',
  },
  accessBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  accessBadgeLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    color: '#FFFFFF',
  },
  managePermissionButton: {
    marginTop: 8,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  managePermissionLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#1C142F',
  },
  managePermissionArrows: {
    flexDirection: 'row',
  },
  profileSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  profileSheetScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  profileSheetContainer: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#4C425F',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 24,
    gap: 10,
    maxHeight: '60%',
  },
  profileSheetHandle: {
    width: 60,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    alignSelf: 'center',
    marginBottom: 12,
  },
  profileSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
  },
  profileSheetItemActive: {
    borderColor: '#6ECCFF',
    backgroundColor: 'rgba(126, 204, 255, 0.08)',
  },
  profileSheetAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  profileSheetName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  profileSheetStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  profileSheetStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#6DE7A4',
  },
  profileSheetStatus: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#C8C5DB',
  },
  profileSheetActions: {
    marginLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileSheetCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#6ECCFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileSheetAdd: {
    marginTop: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  profileSheetAddLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#1C142F',
  },
  profileSheetPowered: {
    marginTop: 6,
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#EADFC6',
    textAlign: 'center',
  },
  profileSheetBrand: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 18,
    color: '#EADFC6',
    textAlign: 'center',
    letterSpacing: 1,
  },
  alertsWrapper: {
    gap: 14,
  },
  alertCard: {
    borderRadius: 20,
    backgroundColor: '#4E4862',
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  alertIconWrapper: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertIconRequest: {
    backgroundColor: 'rgba(255, 199, 95, 0.16)',
  },
  alertIconWarning: {
    backgroundColor: 'rgba(110, 204, 255, 0.16)',
  },
  alertIconSummary: {
    backgroundColor: 'rgba(124, 232, 156, 0.16)',
  },
  alertContent: {
    flex: 1,
    gap: 6,
  },
  alertTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  alertTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 13,
    color: '#FFFFFF',
    flexShrink: 1,
  },
  alertStatus: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#F6C66E',
    marginTop: 2,
  },
  alertBody: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#D9D6E8',
    lineHeight: 18,
  },
  alertMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  alertMetaDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#6ECCFF',
  },
  alertMetaText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 11,
    color: '#C8C5DB',
  },
  alertsLoading: {
    marginTop: 10,
    padding: 18,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  placeholderCard: {
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    gap: 6,
  },
  placeholderTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  placeholderBody: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#C8C5DB',
    lineHeight: 20,
  },
  statsWrapper: {
    gap: 16,
  },
  statsCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    gap: 6,
  },
  statsTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#DCD8EE',
  },
  statsValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 24,
    color: '#FFFFFF',
  },
  statsDelta: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#6ECCFF',
  },
  insightRow: {
    flexDirection: 'row',
    gap: 12,
  },
  insightCard: {
    flex: 1,
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  insightPrimary: {
    backgroundColor: '#2D4461',
  },
  insightWarning: {
    backgroundColor: '#5A3A52',
  },
  insightIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  insightTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#E4E1F4',
  },
  insightValue: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 24,
    color: '#FFFFFF',
  },
  analysisCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    gap: 12,
  },
  analysisHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  analysisActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  analysisTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  analysisTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  analysisTabActive: {
    backgroundColor: '#3A2F4E',
  },
  analysisTabLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: '#B8B3CB',
  },
  analysisTabLabelActive: {
    color: '#FFFFFF',
  },
  analysisSummary: {
    gap: 10,
  },
  analysisMode: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#B4F0C8',
  },
  analysisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  analysisLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#C8C5DB',
  },
  analysisValue: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 13,
    color: '#E6E3F5',
  },
  settingsCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    gap: 12,
  },
  settingsList: {
    gap: 12,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  settingsSubtitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#C8C5DB',
    lineHeight: 18,
  },
  settingsToggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    padding: 4,
    justifyContent: 'center',
  },
  settingsToggleOn: {
    backgroundColor: '#6ECCFF',
    borderColor: '#6ECCFF',
  },
  settingsThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1C142F',
    alignSelf: 'flex-start',
  },
  settingsThumbOn: {
    alignSelf: 'flex-end',
    backgroundColor: '#FFFFFF',
  },
  profileScreenContainer: {
    alignItems: 'center',
    gap: 18,
    paddingVertical: 18,
  },
  profileAvatarLg: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  profileAvatarEdit: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileScreenName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  profileScreenEmail: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: '#D0CBE5',
  },
  profileMenu: {
    width: '100%',
    gap: 12,
  },
  profileMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  profileMenuIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMenuTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  profileMenuSubtitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#C8C5DB',
    marginTop: 2,
  },
  signOutButton: {
    marginTop: 6,
    width: '100%',
    borderRadius: 26,
    paddingVertical: 14,
    backgroundColor: '#FF6F6F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  signOutLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: '#FFFFFF',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(15, 10, 25, 0.9)',
  },
  bottomNavItem: {
    alignItems: 'center',
    gap: 6,
  },
  bottomNavIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavIconActive: {
    backgroundColor: '#7FDBFF',
  },
  bottomNavLabel: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 11,
    color: '#A8A2C2',
  },
  bottomNavLabelActive: {
    color: '#FFFFFF',
  },
  bottomNavBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#F04E5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavBadgeLabel: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 10,
    color: '#FFFFFF',
  },
});


export default styles;
